### ISSUE TITLE
WE NEED A TITLE

### ISSUE THREAD

**Issue by ryanisaacg** [fwumdesoft/project8-java#102]
Is Cosmic Circuits good?

**Comment by inser7Name** [comment]
Space Circuits
Cosmic Circuitry
Station of Doom

**Comment by inser7Name** [comment]
Those are pretty crap, but ya know, I tried

**Comment by ryanisaacg** [comment]
I think Cosmic Circuits / Circuitry is good. I prefer Circuitry?
