### ISSUE TITLE
There should be sprites for the player

### ISSUE THREAD

**Issue by ryanisaacg** [fwumdesoft/project8-java#2]
- Each sprite should have ~~a version where it faces in each cardinal direction~~
- ~~Idle sprite~~
- ~~Walking sprite~~
- Interacting sprite

The sprites should all be animated and draw correctly given the game state.

**Comment by ryanisaacg** [comment]
There's no point in doing this until #32 is finished.

**Comment by ryanisaacg** [comment]
@Ryguy9999 I know you think you're bad at drawing humans, but give it a try anyway?

**Comment by Ryguy9999** [comment]
We said the only animation needed is walking right? I don't want to close the Issue prematurely, but if so, then consider this issue closed.
