### ISSUE TITLE
There should be sprites for doors

### ISSUE THREAD

**Issue by ryanisaacg** [fwumdesoft/project8-java#3]
- The sprite should face horizontally to allow for easy rotation.
- It should have a closed version and an open version.
- There should be an open animation.

The door should play an open animation when the player is adjacent, and be open when the player is next to it.

**Comment by ryanisaacg** [comment]
Depends heavily on the completion of issue #5

**Comment by Ryguy9999** [comment]
"face horizontally" The sprite should be oriented that walking through it is horizontal, or that its closed state creates a horizontal line?

**Comment by Ryguy9999** [comment]
Ok, I added a graphic, but we may need to adjust some things. We'll see.
