### ISSUE TITLE
Should we lock the different types of component values?

### ISSUE THREAD

**Issue by ryanisaacg** [fwumdesoft/project8-java#30]
For example, should a resistor be able to have any resistance, or just a restricted integer from 1 to 10 ohms? 

I'd prefer the latter, because it makes spawning items and showing values in the inventory easier.

**Comment by Ryguy9999** [comment]
Um, didn't we discuss in Physics a solution that allowed any resistance?

**Comment by ryanisaacg** [comment]
Not really, we never decided how to fix the inventory / placing resistors as far as I remember.

**Comment by ryanisaacg** [comment]
Also, it would be very convenient if the lamps all had 1 resistance and varying current required to activate or 1 current required to activate and varying resistances.

**Comment by Ryguy9999** [comment]
However, lamps will probably be the least common component (or maybe batteries) so even if every lamp is different, it's not that bad. The only component which every one being different would break the UI would be resistors, but more likely than not, their resistances will be whole numbers

**Comment by ryanisaacg** [comment]
What I'm saying is that if lamps have two variables that can change (resistance + required current) then it'll be terrible to deal with them.
