### ISSUE TITLE
Overworld animations

### ISSUE THREAD

**Issue by ryanisaacg** [fwumdesoft/project8-java#32]
The renderer should provide a few frames of animation for every turn the player takes.

**Comment by ryanisaacg** [comment]
@Ryguy9999 Do we even want to go through with this?

**Comment by Ryguy9999** [comment]
HAHAHA! I DID IT! Would you mind taking a look at door and player frame animation again? Or at least help me out, since I'm not sure what I should do about it.

**Comment by ryanisaacg** [comment]
What do you meant, "you did it?"
