### ISSUE TITLE
CircuitComponent should provide a Blank option

### ISSUE THREAD

**Issue by ryanisaacg** [fwumdesoft/project8-java#33]
To make input and rendering easier, the CircuitComponent should have an option for a blank space that the player can place resistors, batteries, and lamps into. Otherwise, it would be hard to determine what would be a legal placement.

Unless we want to let the player join any two wires, which could be interesting but difficult.

**Comment by Ryguy9999** [comment]
hm, this is what isChangeable is for, except empty spaces are null so they cant have isChangeable... we may just have to switch representation from null component to component with null Type

**Comment by ryanisaacg** [comment]
That sounds like a good implementation, do you want to do it or should I?

**Comment by Ryguy9999** [comment]
um, i guess i can

**Comment by ryanisaacg** [comment]
If the renderer breaks, I'll fix it, just handle everything else.

**Comment by Ryguy9999** [comment]
well actually, isnt the only that needs to be refactored to this standard the solver?

**Comment by ryanisaacg** [comment]
The renderer needs to know to draw a slot that you can edit and the editor needs to know how to place it, but I'll handle those.

**Comment by ryanisaacg** [comment]
Turns out combining your change with mine actually fully solved the issue.
