### ISSUE TITLE
Overworld should generate pickups

### ISSUE THREAD

**Issue by ryanisaacg** [fwumdesoft/project8-java#4]
The overworld should generate pickups such as resistors and computer chips placed throughout. When the player moves to that square, the resistor or chip should be picked up and added to the inventory.

**Comment by Ryguy9999** [comment]
UPDATE: Partial completion: Bags now render and generate (somewhat generously?), but cannot be interacted with

**Comment by Ryguy9999** [comment]
Annd... done :D
