### ISSUE TITLE
The game should end when the player is in the escape pod

### ISSUE THREAD

**Issue by ryanisaacg** [fwumdesoft/project8-java#50]
Once all the terminals have been fixed and the player is in the escape pod, a credits scene should be played.

**Comment by ryanisaacg** [comment]
Depends on #49

**Comment by inser7Name** [comment]
What exactly should happen when the game ends?

**Comment by ryanisaacg** [comment]
I guess a credits sequence? For now, just make a method in overworld that returns if the game is over.

**Comment by inser7Name** [comment]
gameWon boolean added
