### ISSUE TITLE
Tiles and Mods slight refactor

### ISSUE THREAD

**Issue by Ryguy9999** [fwumdesoft/project8-java#59]
Fire suppression should be a tile not a mod, since you can't walk through fire extinguishers. Also, doorBroken and doorFixed are mods that should become broken and fixed to be useful to every circuitable machine.

**Comment by ryanisaacg** [comment]
This appears to be fixed, but I'm not quite sure, so I'll let you close it if it is.

**Comment by ryanisaacg** [comment]
Hm, it isn't fixed for all extinguishers? This is weird.

**Comment by Ryguy9999** [comment]
I believe this should now be complete
