### ISSUE TITLE
Make sure credits are correct

### ISSUE THREAD

**Issue by inser7Name** [fwumdesoft/project8-java#82]
We need to properly credit people/stuff we used

**Comment by inser7Name** [comment]
I know I did only code, ryan g did only code (I think), and other ryan did code and art. Also, do we have to credit anything other than us like libgdx?

**Comment by ryanisaacg** [comment]
We have to credit libGDX, and actually all of us did art.

I drew the floor texture/player (forgot when Alex asked me), Alex did walls, Ryan C did everything else.

**Comment by ryanisaacg** [comment]
Looks like it was fixed by 1629434d719c85fa21b0187d0b31952adc915a32
